In [2]:
import numpy as np

In [3]:
s = np.array(5)

In [4]:
s

array(5)

In [5]:
s.shape

()

In [6]:
type(s)

numpy.ndarray

In [7]:
d = np.array((1,5))

In [8]:
d.shape

(2,)

In [9]:
v = np.array([1,2,3])

In [10]:
v

array([1, 2, 3])

In [11]:
s.item()

5

In [12]:
v.item()

ValueError: can only convert an array of size 1 to a Python scalar

In [13]:
v.shape

(3,)

In [14]:
v = np.array([[1,2,3]])

In [15]:
v.shape

(1, 3)

In [16]:
v = np.array([[1],[2],[3]])

In [17]:
v.shape

(3, 1)

In [18]:
v = np.array([1,2,3,4])

In [19]:
x = v [1:  ]

In [20]:
x

array([2, 3, 4])

In [21]:
x1 = v [None, :]

In [22]:
x1

array([[1, 2, 3, 4]])

In [23]:
a = np.array([1,2,3])

In [24]:
b = np.array([1,2,3,4])

In [25]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4])

In [3]:
x2 = v [None, :]
x3= v [:, None]

In [4]:
x2

array([[1, 2, 3, 4]])

In [5]:
x3

array([[1],
       [2],
       [3],
       [4]])

In [6]:
w = x2.min

In [7]:
w

<function ndarray.min>

In [8]:
for x in x2:
    print x

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(x)? (<ipython-input-8-3b4cbb51342b>, line 2)

In [9]:
for x in x2:
    print (x)

[1 2 3 4]


In [10]:
for x in x3:
    print x

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(x)? (<ipython-input-10-5c9c44b08470>, line 2)

In [11]:
for x in x3:
    print (x)

[1]
[2]
[3]
[4]


In [12]:
xas =numpy.x2min()

NameError: name 'numpy' is not defined

In [13]:
xas =np.x2min()

AttributeError: module 'numpy' has no attribute 'x2min'

In [14]:
xas =numpy.min(x2)

NameError: name 'numpy' is not defined

In [15]:
xas =np.min(x2)

In [16]:
xas

1

In [17]:
xa23s =np.max(x2)

In [18]:
xa23s

4

In [19]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = None
    s = np.array(inputs)
    input_array = s [None, :]
    pass

    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = None
    min = np.min(input_array)
    inputs_minus_min = input_array - min
    
    

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = None
    max = np.max(input_array)
    inputs_div_max = input_array / max
    

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    try:
        x = m1.shape
        y = m2.shape
        z = np.matmul(m1,m2)
        return z   # how to swap
    except ValueError:
        print("False")
    pass


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    pass
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    average_value = np.mean(input_array) 
    return average_value
    pass


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[-0.14285714  0.28571429  1.        ]]
False
Multiply 1:
None
Multiply 2:
[[14]
 [32]]
False
Multiply 3:
None
Mean == 2.6666666666666665


In [20]:
x2

array([[1, 2, 3, 4]])

In [21]:
yz = x2.shape
yz

(1, 4)

In [22]:
m1_row, m1_col = x2.shape
m1_row,m1_col

(1, 4)

In [23]:
m1_row

1

In [24]:
m1_col

4

In [25]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    n = len(inputs)
    s = np.array(inputs)
    input_array = s.reshape(1,n)
    print("test input array", input_array)

    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    min = np.min(input_array)
    inputs_minus_min = input_array - min
    print("test input minus min", inputs_minus_min)
    
    

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = None
    max = np.max(inputs_minus_min)
    inputs_div_max = inputs_minus_min / max
    print("test div_max", inputs_div_max)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    m1_row, m1_col = m1.shape
    m2_row, m2_col = m2.shape
    if (m1_col == m2_row):
        z = np.matmul(m1,m2)
    elif (m2_col == m1_row):
        z = np.matmul(m2,m1)
    else: return False
    return z


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary

    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    input_array = np.array(values)
    average_value = np.mean(input_array) 
    return average_value



input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

test input array [[-1  2  7]]
test input minus min [[0 3 8]]
test div_max [[0.    0.375 1.   ]]
Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
